<!DOCTYPE html>
<?php
/**
 * @var \Slim\Router $router
 */
?>

<html>
    <head>
        <meta charset="utf-8"/>
        <title>代挖矿</title>
    </head>
    <body>
    <form action="<?php echo $router->pathFor('addCode');?>" method="post">
        <input type="text" name="code" id="code" placeholder="挖矿码">
        <button type="submit">添加挖矿码</button>
    </form>
<!--    <form action="--><?php //echo $router->pathFor('deleteCode');?><!--" method="post">-->
<!--        <input type="text" name="code" id="code" placeholder="挖矿码">-->
<!--        <button type="submit">删除挖矿码</button>-->
<!--    </form>-->
<!---->
<!--    <form action="--><?php //echo $router->pathFor('checkoutCode');?><!--" method="post">-->
<!--        <input type="text" name="code" id="code" placeholder="挖矿码">-->
<!--        <button type="submit">查看挖矿码</button>-->
<!--    </form>-->

    </body>
</html>
